### ISSUE TITLE
Turn-In-Error

### ISSUE THREAD

**Issue by namratanwani** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#18]
- [x] Facing error: "Turn-In canceled." while pushing the set to the repo through OCR software.

**Comment by AnjaliVijayvargiya** [comment]
when you facing this error, try to configure git settings by following these commands:
git config --system user.name "your github username"
git config --system user.email "your email"

**Comment by AnjaliVijayvargiya** [comment]
As github has changed its security policy. Now, it using some access token instead of password. So, for this, you have to set token. Follow this link : https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token 
create your token. For future reference, you can save this token to a new text file (notepad file). Use this token while cloning and pushing the bookset.
